-- MySQL Script generated by MySQL Workbench
-- Mon Oct 27 15:58:42 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Customer` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Customer` (
  `cust_id` INT NOT NULL,
  `cust_name` VARCHAR(45) NULL,
  `cust_surname` VARCHAR(45) NULL,
  `cust_email` VARCHAR(45) NULL,
  `cust_location` VARCHAR(45) NULL,
  `cust_password` VARCHAR(45) NULL,
  PRIMARY KEY (`cust_id`),
  UNIQUE INDEX `cust_email_UNIQUE` (`cust_email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`location`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`location` ;

CREATE TABLE IF NOT EXISTS `mydb`.`location` (
  `location_id` INT NOT NULL,
  `location_name` VARCHAR(45) NULL,
  PRIMARY KEY (`location_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cust_order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`cust_order` ;

CREATE TABLE IF NOT EXISTS `mydb`.`cust_order` (
  `order_id` INT NOT NULL,
  `grc_items` VARCHAR(45) NULL,
  `location_id` INT NOT NULL,
  `cust_id` INT NOT NULL,
  PRIMARY KEY (`order_id`),
  INDEX `fk_cust_order_location_idx` (`location_id` ASC) VISIBLE,
  INDEX `fk_cust_order_Customer1_idx` (`cust_id` ASC) VISIBLE,
  CONSTRAINT `fk_cust_order_location`
    FOREIGN KEY (`location_id`)
    REFERENCES `mydb`.`location` (`location_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cust_order_Customer1`
    FOREIGN KEY (`cust_id`)
    REFERENCES `mydb`.`Customer` (`cust_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`department`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`department` ;

CREATE TABLE IF NOT EXISTS `mydb`.`department` (
  `department_id` INT NOT NULL,
  `department_name` VARCHAR(45) NULL,
  PRIMARY KEY (`department_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`staff`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`staff` ;

CREATE TABLE IF NOT EXISTS `mydb`.`staff` (
  `staff_id` INT NOT NULL,
  `staff_name` VARCHAR(45) NULL,
  `staff_surname` VARCHAR(45) NULL,
  `staff_email` VARCHAR(45) NULL,
  `phone_nmr` INT NULL,
  `position` VARCHAR(45) NULL,
  `staff_password` VARCHAR(45) NULL,
  `department_id` INT NOT NULL,
  PRIMARY KEY (`staff_id`),
  UNIQUE INDEX `staffcol1_UNIQUE` (`phone_nmr` ASC) VISIBLE,
  UNIQUE INDEX `staff_email_UNIQUE` (`staff_email` ASC) VISIBLE,
  INDEX `fk_staff_department1_idx` (`department_id` ASC) VISIBLE,
  CONSTRAINT `fk_staff_department1`
    FOREIGN KEY (`department_id`)
    REFERENCES `mydb`.`department` (`department_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`category` ;

CREATE TABLE IF NOT EXISTS `mydb`.`category` (
  `category_id` INT NOT NULL,
  `category_name` VARCHAR(45) NULL,
  PRIMARY KEY (`category_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`new_product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`new_product` ;

CREATE TABLE IF NOT EXISTS `mydb`.`new_product` (
  `product_id` INT NOT NULL,
  `product_name` VARCHAR(45) NULL,
  `min_qty` VARCHAR(45) NULL,
  `max_qty` VARCHAR(45) NULL,
  `category_id` INT NOT NULL,
  `staff_id` INT NOT NULL,
  PRIMARY KEY (`product_id`),
  INDEX `fk_new_product_category1_idx` (`category_id` ASC) VISIBLE,
  INDEX `fk_new_product_staff1_idx` (`staff_id` ASC) VISIBLE,
  CONSTRAINT `fk_new_product_category1`
    FOREIGN KEY (`category_id`)
    REFERENCES `mydb`.`category` (`category_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_new_product_staff1`
    FOREIGN KEY (`staff_id`)
    REFERENCES `mydb`.`staff` (`staff_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`update_inventory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`update_inventory` ;

CREATE TABLE IF NOT EXISTS `mydb`.`update_inventory` (
  `update_id` INT NOT NULL,
  `quantity` INT NULL,
  `location_id` INT NOT NULL,
  `category_id` INT NOT NULL,
  `staff_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  PRIMARY KEY (`update_id`),
  INDEX `fk_update_inventory_location1_idx` (`location_id` ASC) VISIBLE,
  INDEX `fk_update_inventory_category1_idx` (`category_id` ASC) VISIBLE,
  INDEX `fk_update_inventory_staff1_idx` (`staff_id` ASC) VISIBLE,
  INDEX `fk_update_inventory_new_product1_idx` (`product_id` ASC) VISIBLE,
  CONSTRAINT `fk_update_inventory_location1`
    FOREIGN KEY (`location_id`)
    REFERENCES `mydb`.`location` (`location_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_update_inventory_category1`
    FOREIGN KEY (`category_id`)
    REFERENCES `mydb`.`category` (`category_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_update_inventory_staff1`
    FOREIGN KEY (`staff_id`)
    REFERENCES `mydb`.`staff` (`staff_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_update_inventory_new_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `mydb`.`new_product` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- Seed categories (from screenshot)
INSERT INTO `categories` (`category_name`) VALUES
('Meat'),
('Poultry'),
('Fish'),
('Produce'),
('Dairy'),
('Bakery'),
('Starch'),
('Beverages'),
('Cleaning Supplies'),
('Electronics'),
('Other');

-- Seed departments (from screenshot)
INSERT INTO `department` (`department_name`) VALUES
('Inventory Management'),
('Sales'),
('Customer Service'),
('Logistics'),
('Administration');

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
